site:
  title: Neo4j Training
  url: /graphacademy/online-training

content:
  sources:
  - url: https://github.com/neo4j-contrib/training-v3.git
    branches: 'master'
    start_paths:
    - 'modules/home'
    - 'modules/4.0-intro-neo4j'
    - 'modules/graph-data-modeling'
    - 'modules/4.0-implementing-graph-data-models'
    - 'modules/4.0-neo4j-admin'
    - 'modules/4.0-cypher-query-tuning'
    - 'modules/4.0-intro-graph-algos'
    - 'modules/online-training-v2'
    - 'modules/neo4j-administration'
    - 'modules/gds-applied-algos'
    - 'modules/datascience'
    - 'modules/applied-algos'

ui:
  bundle:
    url: ui/build/ui-bundle.zip
    snapshot: true

urls:
  html_extension_style: indexify

asciidoc:
  extensions:
  - ./extensions/remote-include/remote-include-processor
  - ./extensions/macros/macros
  attributes:
    experimental: ''
    page-component: training
    page-theme: training
    page-cdn: /static/assets
    page-canonical-root: /training-welcome
    page-breadcrumbs:
      - name: Neo4j Training
        url: /training-welcome

