name: Publish

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
    - master

jobs:
  build_developer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    # Build Content
    - run: npm install
    - run: npm run lint
    - run: npm run build:production


    # Move _ to static/assets
    - run: mkdir -p build/site/static
    - run: mv build/site/_ build/site/static/assets

    # Sync all files to
    - name: Sync to Static
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: static.neo4j.com
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: 'build/site/'

    # Sync to Dev bucket
    - name: Sync to Dev bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.DEV_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.DEV_AWS_S3_REGION }}
        SOURCE_DIR: 'build/site/'

    # Index into Algolia
    - run: npm run index
      env:
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        ALGOLIA_INDEXES: ${{ secrets.ALGOLIA_INDEXES }}
