name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v2.1.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install --prefix ui
      - run: npm run lint --prefix ui
      - run: npm run build --prefix ui
      - run: mv ui/build/ui-bundle.zip ui/build/ui-bundle-${UI_BUNDLE_VERSION}.zip
        env:
          UI_BUNDLE_VERSION: ${{ github.ref }}

      - name: Sync UI Bundle to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --include '*.zip'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'
          SOURCE_DIR: 'ui/build'
          DEST_DIR: 'build'
